### ISSUE TITLE
A child task can submit its ancestor after a delay

### ISSUE THREAD

**Issue by adriancole** [NirmataOSS/workflow#11]
I'd like to create a DAG that repeats after a delay. The period would be fixed, but the delay would be relative to the completion time of its ancestor.

An example which roughly describes behavior which will deviate slightly in calculation. Given a terminal task completes, and the period of the DAG is 3 minutes. One minute elapsed since its root node completed, it would resubmit the root node after a delay of 2 minutes.

It is fine to use job metadata to lookup period, etc. Main thing I'm looking for is the best flow to resubmit on an interval, and also how to cancel this loop.

**Comment by Randgalt** [comment]
Work is done and tested. Under the branch "delay-queue" for now. I need to write the doc and prep a new release. Will do soon.

**Comment by Randgalt** [comment]
https://github.com/NirmataOSS/workflow/pull/12

**Comment by Randgalt** [comment]
I don't know why I didn't think of this earlier. Curator also supports a priority queue. I just released a 0.4.1 version that supports both delay and priority queues.

**Comment by adriancole** [comment]
Going from great to greater! Thanks!
