### ISSUE TITLE
New feature request - Allow custom workflow task executors

### ISSUE THREAD

**Issue by JimBugwadia** [NirmataOSS/workflow#22]
Currently workflow task executor threads are launched from the thread that schedules the workflow. 

This created a situation, where when a workflow thread was created from a thread handling a user operation, it inherited security context data (we are using Apache Shiro which uses an InheritableThreadLocal) from the user operation thread. Since the workflow task executors are subsequently reused, this can lead to problems due to cached thread local data.

A solution would be to allow passing in a custom ExecutorService, so users can implement their own logic in ThreadPoolExecutor.beforeExecute  and / or ThreadPoolExecutor.afterExecute.

**Comment by Randgalt** [comment]
@JimBugwadia please review and let me know that this is OK and I'll make a release.

**Comment by JimBugwadia** [comment]
Thanks for the quick turnaround! The interface looks good. 

A few questions on the behavior:

1. If a custom executor is specified, how does this impact task allocation. For example if an implementation declares it can handle 10 concurrent tasks, are we using task completion to throttle, or the number of tasks scheduled / running?

2. Are there any restrictions / guidelines on the custom executor's behavior? Is it best to have a fixed pool size to match the concurrency level?

**Comment by Randgalt** [comment]
The Executor is expected to execute the task and return. The calling thread waits for it to complete using a FutureTask. 

If using a pool, the pool should probably have as many threads as configured Workflow Executors. Otherwise, the Executors will block until a thread is available.

**Comment by JimBugwadia** [comment]
Ok, makes sense. Thanks!
