### ISSUE TITLE
workflowManager.getRunInfo() take a long time to complete

### ISSUE THREAD

**Issue by dtoledo67** [NirmataOSS/workflow#23]
I have edited the original issue: the call taking a long time to complete is getRunInfo(), not getAdmin() ...

**Background information:**
Before creating a workflow, I verify if there is already a similar workflow pending. I do that to avoid having tasks pilling up in zookeeper. When a task is created, I add a key in the metadata of the task. This key is the combination of a task type and the id of the resource for which the task is going to be executed. Example: if a task is in charge of pinging a host then the key would be something like "PingHostTask-<hostid>". Before creating a ping task for a host, I first call getRunInfo() to see if there is already a task pending for this host. Here is the code:

 public boolean isSimilarTaskPending(TaskType taskType, List<RunInfo> runInfos,String key) {
        for (RunInfo runInfo: runInfos) {
            if (runInfo.isComplete() ) {
                continue;
            }
            RunId runId = runInfo.getRunId();
            Map<TaskId,TaskDetails> taskDetails = _admin.getTaskDetails(runId);
            Set<TaskId> taskIds = taskDetails.keySet();
            for (TaskId taskId: taskIds) {
                TaskDetails details = taskDetails.get(taskId);
                TaskType type = details.getTaskType();
                if (type == taskType) {
                    Map<String,String> metadata = details.getMetaData();
                    String taskKey = metadata.get("taskKey");
                    if ((taskKey != null) && (taskKey.equals(key) )) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

**Problem: **
In our environment, the call to workflowManager.getRunInfo()  to get the list of runInfos takes 15 to 20 seconds to complete.

Our zookeeper cluster has around 100K nodes but only few hundreds are  related to workflows. And even less are related to a particular type of workflow (about 1500 nodes in ../runs for this workflow)Why is this call taking so long? Do you have an alternative approach to recommend to check if a task is already pending?

**Comment by Randgalt** [comment]
workflowManager.getAdmin() would return instantly, it doesn't do anything. It would be interesting to know how many runs are in ```runInfos``` and how long the call to ```getRunInfo()``` takes.

**Comment by Randgalt** [comment]
So there are 1,500 runs being checked? I'm not surprised that it takes a while. That will result in 1,500 separate API calls to ZooKeeper to get data. But, 15-20 seconds seem long. Is it literally the getRunInfo() method that is taking 15-20 seconds? 

I notice in your call that you're also calling getTaskDetails(). Internally, this makes a duplicate call to ZK. You can optimized your code by doing manually getting the runIds without calling getRunInfo(). I can provide an API for this if you want. This would double the speed (at minimum) of what you're doing.

**Comment by Randgalt** [comment]
OK - I added a getRunIds() method to admin. Please try using that instead of getRunInfo() and let me know how it works for you.

**Comment by dtoledo67** [comment]
Let me explain what I am trying to do so you can recommend the best
approach. I want to avoid creating a workflow for given resource if there
is already  the same type of workflow for the same resource not yet
executed. To achieve this, I store a key in the metadata of the task, a
combination of the  task type and the resource id. Before creating a new
workflow for the resource, I want to retrieve the list of workflows not
executed and then I search if one of them as the same key. Hope it make
sense ...

**Comment by Randgalt** [comment]
@dtoledo67 can you use multiple WorkflowManagers for this? If that's not an option I can think of something else.

**Comment by Randgalt** [comment]
Also @dtoledo67, have you tried the new getRunIds() method to see if it helps?

**Comment by dtoledo67** [comment]
I should be able to try this in our production platform within a couple of
days. I'll let you know.

**Comment by Randgalt** [comment]
Any update?

**Comment by dtoledo67** [comment]
Jordan, I tried the getRunIds() call. The call is faster that the
getRunInfo(). But it doesn't solve the problem because I need to check if
the task is completed or not which mean retrieving the runInfo for each
task (runInfo.isComplete())

Coming back to the call admin.getRunInfo(), I see than  when there is
around 1K entries then the call take about 10 seconds. On my side, I am
trying to see if it is normal to have always around 1K entries. Would
filtering by task type make this faster? (I always execute this call for a
given task type). Probably not since you  have to fetch the node
information to figure out the task type.

**Comment by Randgalt** [comment]
Maybe instead of only using UUIDs we could allow custom ID generation for nodes so that you could encode some type info in the ID. Thoughts?

**Comment by dtoledo67** [comment]
Yes, that would work.

**Comment by Randgalt** [comment]
Please test with the new submitTask() and submitSubTask() APIs and let me know if that works for you.

**Comment by Randgalt** [comment]
FYI - use RunId.newRandomIdWithPrefix()

**Comment by Randgalt** [comment]
@dtoledo67 did the new API work for you?

**Comment by dtoledo67** [comment]
Yes, it worked really well. The total execution time for the tasks creation is now around 50ms compared to  10+ seconds ... Thank you!
