### ISSUE TITLE
New feature request - workflow diagnostics

### ISSUE THREAD

**Issue by JimBugwadia** [NirmataOSS/workflow#25]
We are running into a situation where task execution occasionally stops. When this happens, would be great to run a diagnostic check and report information on a workflow, including number or registered executors and their state to help isolate the root cause.

**Comment by Randgalt** [comment]
Please test the code I just pushed. Have a look at the test class WorkflowManagerStateSampler for an example of a sampling state checker. You can copy that class or write something based on it.

**Comment by JimBugwadia** [comment]
Will the newly added 'WorkflowAdmin.getWorkflowManagerState' work with prior versions? Or, is the state a new attribute requiring the scheduling and execution to also use the updated code?

**Comment by Randgalt** [comment]
Yeah it works with old versions. It only analyzes the manager it's called from. 

====================
Jordan Zimmerman

**Comment by JimBugwadia** [comment]
Thanks! This works and I am able to retrieve the state. Here is what I got back: 

WorkflowManagerState{isConnectedToZooKeeper=true, schedulerState=LATENT, consumersState=[]}

Can you please explain the schedule and consumer states?

**Comment by Randgalt** [comment]
That means that that manager is not the scheduler. More importantly it means it has no task executors. Any idea why?

====================
Jordan Zimmerman

**Comment by JimBugwadia** [comment]
I connected a new WorkflowManager, from a test program solely to query the
state of the workflow.

Is there a way we can print the state of all other WorkflowManager
instances from this?

Thanks,

Jim

**Comment by Randgalt** [comment]
No. That would require major work

====================
Jordan Zimmerman

**Comment by Randgalt** [comment]
OK if I close this?

**Comment by JimBugwadia** [comment]
Yes, thanks!
