### ISSUE TITLE
JsonSerializer.getTask()  is not visible

### ISSUE THREAD

**Issue by Fei-Guang** [NirmataOSS/workflow#26]
>>>you can create task objects programmatically or via a file/stream. To load via file/stream, you can use >>>the utility JsonSerializer.getTask()

but JsonSerializer.getTask()  is not visible

**Comment by Randgalt** [comment]
Yes, it looks like the doc is wrong and the APIs are wrong. I'll have a look at fixing this.

**Comment by Randgalt** [comment]
For now, use the following code to load from a file. I'll work on a better API and doc soon:

```
String json = ... // read the JSON from your file
JsonSerializerMapper jsonSerializerMapper = new JsonSerializerMapper();
Task task = jsonSerializerMapper.get(jsonSerializerMapper.getMapper().readTree(json), Task.class);
```
