### ISSUE TITLE
Graceful shutdown of one workflow instance.

### ISSUE THREAD

**Issue by gs-rchejerla** [NirmataOSS/workflow#29]
I have one use case, where I need to tell worflow-manager to stop listening to new tasks and complete already running tasks. 

I have checked all APIs available ,but I could not find any solution for it. If you could help me on this use case that would be very great.

**Comment by Randgalt** [comment]
You are in control of submitting new tasks. So, you could just stop submitting new tasks and then use the admin APIs to watch for current tasks to finish. Does that work for you?

**Comment by gs-rchejerla** [comment]
Thank you for response.
In my use case, there are set of workflow instances running. I wanted to take down one instance without affecting other workflow instance. 

I can very well kill that instance I wanted to take down, according to Nirmata's design other instances will pick-up running tasks(if idempotent) automatically. 

But, in my case, these tasks are very time consuming ones, so I don't want to terminate them abnormally. So I was looking for any other ways to tell workflow manager to stop listening to new tasks, then I can wait till completion of already running tasks and terminate that instance.

Thank you again.

**Comment by Randgalt** [comment]
OK - it's definitely possible. I don't have time to do it right now. I'd appreciate a PR or I'll get to it when I can.

**Comment by gs-rchejerla** [comment]
I forked the project, will add the feature of stopping workflow gracefully in workflowmanager API. 
Before I start, could you please tell me, if any thing I need to know.

Thank you.

**Comment by Randgalt** [comment]
You'd:

- Add an API to `WorkflowManager` - something like `gracefulShutdown(maxWait)`
- The main work is in `SimpleQueue` - Call shutdown on the executorService then awaitTermination

Something like that

**Comment by gs-rchejerla** [comment]
Thank you for the quick response, will send pull request once done with that.
