### ISSUE TITLE
Scheduler stops receiving events from PathChildrenCache when associated ZK path was deleted and later recreated

### ISSUE THREAD

**Issue by lalalawoo** [NirmataOSS/workflow#33]
We sometimes have task execution issues, which could be summarized as the following two types.

Description | Task be submitted but never be executed and left in the queue.
-- | --
Impact | After that no task with same task key could be submitted. Task of other type using same workflow path would also have same issue.
Workaround | Delete the whole path in ZK, and restart the service

Description | Task be executed successfully but not be auto cleaned
-- | --
Impact | After that no task with same task key could be submitted. Task with different task key, and task of other type using same workflow path, would not be impacted
Workaround | Restart the service instance on which the scheduler is running currentlyFor single instance service, just restart the service

More details are described here  https://docs.google.com/document/d/1uf4RARRjwfy8V_AfOGvoNj6BWKMr32HtSrcNw86irwY/edit?usp=sharing

The root cause of these issues, seems to be that ZK path would be auto-deleted and later when it's recreated the Scheduler could no longer receive the event and consequently could not handle the change of task node in ZK path.

Found similar issue ticket on Curator dashboard https://issues.apache.org/jira/browse/CURATOR-388.

Would provide the test code later.

**Comment by Randgalt** [comment]
Thanks for the detailed report. I'll try to get to this in the next few days. I'd like to try to get a test that reproduces first. So, if you get to that before me that would help.

**Comment by lalalawoo** [comment]
Here attached the test case which could reproduce the problem. 
Since I got some issue using TestServer to reproduce the problem, instead I use real Zookeeper server in the test.
Zookeeper Server : zookeeper-3.5.1-alpha
Curator library : curator-framework-3.2.1, curator-client-3.2.1
Nirmata workflow libary : nirmata-workflow-0.9.0
[TestWorkflow.txt](https://github.com/NirmataOSS/workflow/files/1572159/TestWorkflow.txt)
_(java source file not allowed here, replace .txt with .java to use it)_

**Comment by Randgalt** [comment]
@lalalawoo you say that your test case reproduces the problem. But, I don't see where I can determine that. How do I know in your test whether it is failing or not?

**Comment by Randgalt** [comment]
FYI - I have a simpler test that exposes the problem as part of this PR: https://github.com/NirmataOSS/workflow/pull/34

**Comment by lalalawoo** [comment]
@Randgalt  here attached the log of the test case. I try to put some explanation in it. Please let me know if you found it's unclear. 
[log_TestWorkflow.txt](https://github.com/NirmataOSS/workflow/files/1577153/log_TestWorkflow.txt)

**Comment by Randgalt** [comment]
OK - in any event - I have a fix for all this. However, it will have to wait for the next Curator release. I'll work on getting that out.

**Comment by lalalawoo** [comment]
Thank you very much!
