### ISSUE TITLE
FAILED_STOP re-executes the task

### ISSUE THREAD

**Issue by JimBugwadia** [NirmataOSS/workflow#4]
The TaskExecutor is re-queing after each failure even if we return as 

new TaskExecutionResult(TaskExecutionStatus.FAILED_STOP, "Failed to execute config stats task");

It is always requeing the task the code in org.apache.curator.framework.recipes.queue.DistributedQueue class

try
{ 
    consumer.consumeMessage(item); 
}
catch ( Throwable e )errorMode.get()
{
    log.error("Exception processing queue item: " + itemNode, e);
    if ( errorMode.get() == ErrorMode.REQUEUE )
    { 
         resultCode = ProcessMessageBytesCode.REQUEUE; break; }
    }
}

**Comment by Randgalt** [comment]
I'm unable to reproduce this. I didn't have a test for FAILED_STOP but I just added one and it works correctly (https://github.com/NirmataOSS/workflow/commit/831be15d7d228cf9f44a54190043b284bc93df5c). 

The code you show above is how exceptions are handled. The message is re-queued on exception, but FAILED_STOP is not an exception.

Can you write a test that shows the problem?

**Comment by JimBugwadia** [comment]
You are right - the previously reported behavior was when an exception was thrown and not when FAILED_STOP  is returned (works correctly then.) 

Closing this. I will add a separate feature request to throttle exceptions as that exhausted resources.
