### ISSUE TITLE
Add failure policy (or similar) to limit retries 

### ISSUE THREAD

**Issue by JimBugwadia** [NirmataOSS/workflow#5]
When an exception is thrown from a task, the task is immediately re-queued. 

Although the root cause is the task code, would be good to have some protection in the workflow framework to prevent resource exhaustion. 

A possible solution would be to have a retry policy { numRetries: 10, retryIntervalInMilli: 1000 } and a sensible default.

**Comment by Randgalt** [comment]
We could do that. The only thing is that there is a ZooKeeper lock being held (assuming idempotent tasks). But, I'll try to add this.

**Comment by Randgalt** [comment]
I'm going to close this. Given that the task executor is already pluggable, this can be added by user code.

**Comment by JimBugwadia** [comment]
Jordan, the problem we ran into a few times is that if the task executor exits unexpectedly, for example when an exception is thrown, it gets  continuously re-executed and the service becomes unusable and eventually exhausts resources. 

If we cannot easily safeguard against this, lets document the behavior and recommend that a task executor should  implement a "try - finally" and always return a valid return code.
