### ISSUE TITLE
Need a way to retrieve the metadata of a task submitted but not executed

### ISSUE THREAD

**Issue by dtoledo67** [NirmataOSS/workflow#6]

**Comment by dtoledo67** [comment]
We should be able to retrieve  the task type as well.

**Comment by Randgalt** [comment]
I just pushed a change that adds this method to the Admin API:

```java
    /**
     * Returns a map of all task details for the given run
     *
     * @param runId run
     * @return task details
     */
    public Map<TaskId, TaskDetails> getTaskDetails(RunId runId);
```

I think this will meet your needs. If not let me know. If it does I'll release a new version.

**Comment by dtoledo67** [comment]
Hi Jordan,

Yes, this is good. The TaskDetails has what I need. You can release it!
Thanks,

Damien

Damien Toledo
Co-founder, VP Engineering
Nirmata <http://www.nirmata.com>

**Comment by Randgalt** [comment]
Done



On March 24, 2015 at 6:39:49 PM, Damien Toledo (notifications@github.com) wrote:

Hi Jordan,

Yes, this is good. The TaskDetails has what I need. You can release it!
Thanks,

Damien

Damien Toledo
Co-founder, VP Engineering
Nirmata <http://www.nirmata.com>
