### ISSUE TITLE
mvn clean install command failing to execute

### ISSUE THREAD

**Issue by narahari92** [NirmataOSS/workflow#7]
while trying to setup development environment, maven build is failing. Error says "gpg: no default secret key: secret key not available. After I checked, I found that for maven-gpg-plugin's passphrase attribute, ${gpg.passphrase} property place holder is used but is not defined in properties section of pom.xml file. Is there something I am missing?

**Comment by Randgalt** [comment]
I put the gpg plugin into a profule. Try now.
